# select compiler test docker image 
# default:
#  image: docker.art.haizhi.com/public/cicd-rust:nightly-2022-04-12-0.0.6
#  tags:


stages:
  - check
  - test


# format and compiler chcek
pre_check:
  stage: check
  script:
    - rustc --version
    - cargo update
    - cargo update -p time@0.3.25 --precise 0.3.23
    - cargo fmt --all --check
    - cargo check --release
    - cargo check --tests --release
  interruptible: true


# unit test for each mod
unit_test:
  stage: test
  script:
    - cargo update
    - cargo update -p time@0.3.25 --precise 0.3.23
    - cargo test


# test SysYCC correctness 
functional_test:
  stage: test
  script:
    - cargo update
    - cargo update -p time@0.3.25 --precise 0.3.23
    - cargo build -r
    - bash scripts/ci_functional_test.sh /home/gitlab-runner/Tools/qemu/riscv-gnu-toolchain/opt-riscv-rv64/bin /usr/bin/qemu-riscv64-static
    
# test SysYCC optimization performance 
performance_test:
  stage: test
  script:
    - echo "todo"
